import { Badge, cn } from "./ui";
import type { CycleStage, MasteryState } from "@/lib/types";

export const MASTERY_META: Record<
  MasteryState,
  { label: string; meaning: string; dot: string; chip: string }
> = {
  red: {
    label: "Red",
    meaning: "Misconception still present",
    dot: "bg-rose-500",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
  },
  yellow: {
    label: "Yellow",
    meaning: "Correct answer, reasoning uncertain",
    dot: "bg-amber-500",
    chip: "border-amber-200 bg-amber-50 text-amber-800",
  },
  green: {
    label: "Green",
    meaning: "Understands and can transfer it",
    dot: "bg-emerald-500",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
  },
  blue: {
    label: "Blue",
    meaning: "Can explain it to someone else",
    dot: "bg-sky-500",
    chip: "border-sky-200 bg-sky-50 text-sky-700",
  },
};

export const STAGE_LABEL: Record<CycleStage, string> = {
  answered: "Answered",
  diagnosed: "Diagnosed",
  repairing: "Repairing prerequisites",
  practising: "ErrorTwin practice",
  "teach-back": "Teach-back attempted",
  resolved: "Resolved",
};

export function MasteryPill({
  state,
  showMeaning = false,
  className,
}: {
  state: MasteryState;
  showMeaning?: boolean;
  className?: string;
}) {
  const meta = MASTERY_META[state];
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[11.5px] font-medium",
        meta.chip,
        className,
      )}
      title={meta.meaning}
    >
      <span className={cn("size-1.5 rounded-full", meta.dot)} aria-hidden="true" />
      {showMeaning ? meta.meaning : meta.label}
    </span>
  );
}

/** The colour key, so the states are never unexplained on screen. */
export function MasteryLegend({ className }: { className?: string }) {
  return (
    <ul className={cn("flex flex-wrap gap-x-4 gap-y-1.5", className)}>
      {(Object.keys(MASTERY_META) as MasteryState[]).map((state) => (
        <li key={state} className="flex items-center gap-1.5 text-[11.5px] text-slate-500">
          <span
            className={cn("size-2 rounded-full", MASTERY_META[state].dot)}
            aria-hidden="true"
          />
          {MASTERY_META[state].meaning}
        </li>
      ))}
    </ul>
  );
}

export function StageBadge({ stage }: { stage: CycleStage }) {
  const tone =
    stage === "resolved" ? "green" : stage === "answered" ? "neutral" : "brand";
  return <Badge tone={tone}>{STAGE_LABEL[stage]}</Badge>;
}

/** Small marker distinguishing live model output from the demo analyzer. */
export function SourceTag({
  source,
  className,
}: {
  source: "llm" | "demo";
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[10.5px] font-medium",
        source === "llm"
          ? "bg-emerald-50 text-emerald-700"
          : "bg-slate-100 text-slate-500",
        className,
      )}
      title={
        source === "llm"
          ? "Generated by the configured language model."
          : "Generated by the built-in demo analyzer — no LLM key is configured."
      }
    >
      {source === "llm" ? "AI analysis" : "Demo analyzer"}
    </span>
  );
}
